zuihou:
  mysql:
    authority:
      database: zuihou_authority_dev
      host: ${zuihou.ip.mysql}
      port: ${zuihou.mysql.port}
    jobs:
      database: zuihou_jobs_dev
      host: ${zuihou.ip.mysql}
      port: ${zuihou.mysql.port}
    port: 3306
    username: root
    password: 6162659

