zuihou:
  log:
    enabled: true
  port:
    nginx: ${server.port}
    eureka: ${EUREKA_PORT:8761}
  ip:
    mysql: ${MYSQL_IP:${spring.cloud.client.ip-address}}
    nginx: ${NGINX_IP:${spring.cloud.client.ip-address}}
    eureka: ${EUREKA_IP:${spring.cloud.client.ip-address}}
  mysql:
    authority:
      database: zuihou_authority_dev
    port: 3306
    username: root
    password: root

