zuihou:
  port:
    nginx: ${server.port}
    eureka: ${EUREKA_PORT:8761}
  ip:
    mysql: ${MYSQL_IP:${spring.cloud.client.ip-address}}
    nginx: ${NGINX_IP:${spring.cloud.client.ip-address}}
    eureka: ${EUREKA_IP:${spring.cloud.client.ip-address}}
  mysql:
    file:
      database: zuihou_file_dev       # 根据环境更改
    port: 3306                  # 根据环境更改
    username: root              # 根据环境更改
    password: root
  file:
    type: LOCAL # FAST_DFS LOCAL


